# Generated by Django 4.0.5 on 2022-06-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_links_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='facebook',
            field=models.URLField(max_length=80),
        ),
        migrations.AlterField(
            model_name='links',
            name='instagram',
            field=models.URLField(max_length=80),
        ),
        migrations.AlterField(
            model_name='links',
            name='linkedin',
            field=models.URLField(max_length=80),
        ),
        migrations.AlterField(
            model_name='links',
            name='twitter',
            field=models.URLField(max_length=80),
        ),
        migrations.AlterField(
            model_name='links',
            name='youtube',
            field=models.URLField(max_length=80),
        ),
    ]
