# Generated by Django 4.0.5 on 2022-06-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_links_facebook_alter_links_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Admin', max_length=250)),
                ('title', models.CharField(default='Admin', max_length=250)),
                ('aboutAdmin', models.TextField()),
                ('who_are_we', models.TextField()),
                ('profilePic', models.ImageField(upload_to='images')),
            ],
        ),
    ]
