# Generated by Django 4.0.5 on 2022-06-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(default='gainwealth@mail.com', max_length=254),
        ),
    ]
