# Generated by Django 4.0.5 on 2022-08-04 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_team_remove_aboutus_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='aboutAdmin',
            new_name='ourmission',
        ),
    ]
