# Generated by Django 4.0.5 on 2022-08-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_aboutadmin_aboutus_ourmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='ourmission',
            new_name='aboutAdmin',
        ),
    ]
