# Generated by Django 4.0.5 on 2022-08-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_ourmission_aboutus_aboutadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='aboutAdmin',
            new_name='ourmission',
        ),
    ]
