# Generated by Django 4.0.5 on 2022-08-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_aboutadmin_aboutus_ourmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='welcome_message',
            field=models.TextField(default='this is the welcome message, pls change it to whatever you want.'),
        ),
    ]
