# Generated by Django 4.0.5 on 2022-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_aboutus_welcome_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='profilepicture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
